theme: jekyll-theme-minimal
title: Martin Miguel’s Research Hub
description: Relevant links to access publications, posters, code and other resources.
show_downloads: false
google_analytics: G-WL8H83GL6T
